### ISSUE TITLE
Path issues on Windows

### ISSUE THREAD

**Issue by ynnoj** [salsify/broccoli-css-modules#1]
I maintain [ember-cli-notifications](https://github.com/stonecircle/ember-cli-notifications). Windows users of our add-on are encountering a fatal path error since we started consuming the awesome [ember-css-modules](https://github.com/stonecircle/ember-css-modules). 

```
The Broccoli Plugin: [CSSModules] failed with:
Error: ENOENT: no such file or directory, open 'C:\C:\Users\ABI\Code\ember-28-test\tmp\cssmodules-input_base_path-J7jK7ZXQ.tmp\0\modules\ember-cli-notifications\styles\globals.css'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at CSSModules.loadPath (C:\Users\ABI\Code\ember-28-test\node_modules\ember-cli-notifications\node_modules\ember-css-modules\node_modules\broccoli-css-modules\index.js:105:20)
```

https://github.com/stonecircle/ember-cli-notifications/issues/100

**Comment by dfreeman** [comment]
Both broccoli-css-modules and ember-css-modules now have automated testing running against Windows, and the 0.5.0 release of each should be Windows-compatible.

**Comment by dfreeman** [comment]
@ynnoj I'm gonna go ahead and close this out since there haven't been any new reports on https://github.com/stonecircle/ember-cli-notifications/issues/100, but feel free to reopen if anything new comes up.
